# landscape short name; use the project slug here
landscapeName: openwalletfoundation
# Update with your membership structure
landscapeMemberClasses:
   - name: Premier Sponsorship
     category: Premier
   - name: General Sponsorship
     category: Platinum
   - name: Associate Sponsorship
     category: Associate
project: a092M00001L18DzQAJ # OpenWallet Foundation
# Name of category for members 
landscapeMemberCategory: OpenWallet Foundation Sponsorship Organization
