## items to fill in
#
# LANDSCAPENAME - your landscape name as it should be displayed ( i.e. 'OSPO Landscape' )
# LANDSCAPESHORTNAME - your landscape name in a short version ( i.e. 'OSPO' )
# PROJECTNAME - the project's name ( i.e. 'TODO Group' )
# DOMAINNAME - the project's domain name ( i.e. 'todogroup.org' or 'openwallet.foundation' or 'camaraproject.org' )
# PROJECTTWITTER
# PROJECTGITHUB - don't include the https://github.com part - just the org and the repo ( i.e. cncf/ospolandscape )
# PROJECTCRUNCHBASE - https://www.crunchbase.com/organization/XXXXX ( XXXX would be specific to the project on Crunchbase )

global:
  # name of the landscape
  name: OpenWallet Foundation Landscape
  # shortname
  short_name: openwalletfoundation
  # repo where this landscape is hosted ( minus the https://github.com part )
  repo: openwallet-foundation
  # URL to the landscape
  website: https://landscape.openwallet.foundation
  # Short domain name for the landscape (usually this would change 'l' for 'landscape'
  short_domain: l.openewallet.foundation
  # Your project's website
  company_url: https://openwallet.foundation
  # General contact email for the landscape
  email: operations@openwallet.foundation
  # Crunchbase entry for your project - fill in 
  self: PROJECTCRUNCHBASE
  meta:
    # Should match name above
    title: OpenWallet Foundation Landscape
    # keep this
    fb_admin: alex.contini.94
    # site description
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    # your project's twitter
    twitter: '@OpenWalletFdn'
    # update if needed
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  # Category for members
  membership: OpenWallet Foundation Member
  # Update for the categories where you won't be showing the open source license ( typically done for members or conformance program members )
  flags:
    hide_license_for_categories:
      - OpenWallet Foundation Member
# Data for the twitter card
twitter:
  search: landscape.openwallet.foundation
  url: https://landscape.openwallet.foundation
  text: OpenWallet Foundation Landscape
# Complete this section for identifying hosted projects of your project, along with member projects
relation:
  label: OpenWallet Foundation Relation
  url: todo
  values:
    - id: hosted
      label: OpenWallet Foundation Projects
      # children to identify maturity levels ( incubation, active, etc ). If there aren't multiple levels, then just complete like below.
      children:
        - id: foundationproject
          label: OpenWallet Foundation Projects
          prefix: PROJECTNAME
          tag: Foundation Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: PROJECTNAME Project
          big_picture_color: rgb(24,54,114)
    - id: company
      label: PROJECTNAME Member
      tag: Company
      big_picture_order: 3
    - id: member
      label: PROJECTNAME Member Products/Projects
      tag: PROJECTNAME Member
    - id: false
      label: Non-PROJECTNAME Member Products/Projects
      url: 'no'
# membership levels
membership:
  # category for project members
Premier:
    name: OpenWallet Foundation
    label: Premier Member
    end_user_label: Premier Memmber
    funding: Premier
    is_large: true
General:
    name: OpenWallet Foundation
    label: General Member
    end_user_label: General Memmber
    funding: General
    is_large: true
Associate: 
    name: OpenWallet Foundation
    label: Associate Member
    end_user_label: Associate Memmber
    funding: Associate
  # category for LF members
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  # update to change the header text
  header: >
    <h1>OpenWallet Foundation Landscape</h1> The OpenWallet Foundation Landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  # don't change this
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
# ads for the landscape. Good opportunity to advertise your project events
ads:
  - url: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=ospo_landscape&utm_medium=web&utm_campaign=kccnceu20
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
# preset searches
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
# sets the rendering of the landscape
big_picture:
  # this is for the main page
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: OpenWallet Foundation Landscape
    fullscreen_header: See the interactive landscape at l.openwallet.foundation
    # add one element for each category in landscape.yml
    elements:
      - type: HorizontalCategory
        category: OpenWallet Foundation Member
        rows: 4
        width: 650
        height: 150
        top: 210
        left: 0
        color: rgb(103,66,18)
        fit_width: true
      # this is a landscape info box; good idea to keep this one
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 210
        left: 665
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the OpenWallet Foundation community, and also shows the member organizations of the OpenWallet Foundation.
            top: 45
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.openwallet.foundation
            top: 95
            left: 10
            font_size: 18
          - type: image
            image: left-logo.svg
            width: 90
            right: 105
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 90
            right: 10
            top: 10
            title: OpenWallet Foundation Logo
# test to make sure the build worked. Identify one landscape item that you know will always be there, preferably towards the top of the rendering
test:
  header: OpenWallet Foundation Landscape
  section: OpenWallet Foundation Member
  logo: airbnb-member.svg # pick any logo to put here
# if you have a common view, create a pre-render to speed the render time up
prerender:
  # good pre-render to always have; embedable member logo list for a website. Renders to /pages/members
  members: /card-mode?category=open-mainframe-project-member-company&grouping=category&embed=yes&style=borderless
